/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo2;

import Clases.Ingeniero;
import Logica.ServicioPersona;
import java.awt.Dimension;
import javax.swing.JComponent;

public class RegistrarIngeniero extends javax.swing.JInternalFrame {
    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).getNorthPane();
    private Dimension dimBarra = null;
    ServicioPersona sPersona = new ServicioPersona();
   
    
    
    public void ocultarBarraTitulo()
    {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI)getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0,0);
        Barra.setPreferredSize(new Dimension(0,0));
        repaint();
        
    }
    public RegistrarIngeniero() {
        initComponents();
        this.ocultarBarraTitulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        LbContraseña = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        LbNick = new javax.swing.JLabel();
        TfCedula1 = new javax.swing.JTextField();
        TFApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        LbCedula1 = new javax.swing.JLabel();
        BtnGuardar2 = new javax.swing.JButton();
        LbNick1 = new javax.swing.JLabel();
        CmbEspecialidad = new javax.swing.JComboBox<>();
        TxtAños = new javax.swing.JTextField();
        LbContraseña1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtEdad1 = new javax.swing.JTextField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitulo.setText("Registrar Ingeniero");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        LbContraseña.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbContraseña.setText("Apellidos :");
        getContentPane().add(LbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        LbNombre.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbNombre.setText("Nombre :");
        getContentPane().add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        LbNick.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbNick.setText("Años de Experiencia:");
        getContentPane().add(LbNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        TfCedula1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        TfCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCedula1ActionPerformed(evt);
            }
        });
        getContentPane().add(TfCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 170, -1));

        TFApellido.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        TFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(TFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));

        txtNombre.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, -1));

        LbCedula1.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbCedula1.setText("Cedula :");
        getContentPane().add(LbCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        BtnGuardar2.setBackground(new java.awt.Color(255, 255, 255));
        BtnGuardar2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        BtnGuardar2.setText("Guardar");
        BtnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, -1, -1));

        LbNick1.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbNick1.setText("Especialidad:");
        getContentPane().add(LbNick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        CmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analista", "Diseñador", "Programador", "Tester", "Documentador", "Arquitecto" }));
        CmbEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CmbEspecialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbEspecialidadItemStateChanged(evt);
            }
        });
        getContentPane().add(CmbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 30));

        TxtAños.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        TxtAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAñosActionPerformed(evt);
            }
        });
        getContentPane().add(TxtAños, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 170, -1));

        LbContraseña1.setFont(new java.awt.Font("Century", 0, 15)); // NOI18N
        LbContraseña1.setText("Edad:");
        getContentPane().add(LbContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 10));

        TxtEdad1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        TxtEdad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdad1ActionPerformed(evt);
            }
        });
        getContentPane().add(TxtEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfCedula1ActionPerformed

    private void TFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFApellidoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    private void GuardarIngeniero(){
         Ingeniero ingeniero = CrearIngeniero();
         if(ingeniero != null)
         {
            Mensaje.MostrarNotificacion(sPersona.GuardarPersona(ingeniero));
         }
    }
    public Ingeniero CrearIngeniero()
    {
        String nombre = txtNombre.getText();
        String apellidos = TFApellido.getText();
        String cedula = TfCedula1.getText();
        String edad = TxtEdad1.getText();
        String especialidad = CmbEspecialidad.getSelectedItem().toString();
        int años = Integer.parseInt(TxtAños.getText());
        Ingeniero ingeniero = new Ingeniero(años, especialidad, cedula, nombre, apellidos, edad);
        return ingeniero;
    }
     
     
    private void BtnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardar2ActionPerformed
           GuardarIngeniero();
    }//GEN-LAST:event_BtnGuardar2ActionPerformed

    private void CmbEspecialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbEspecialidadItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbEspecialidadItemStateChanged

    private void TxtAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAñosActionPerformed

    private void TxtEdad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdad1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar2;
    private javax.swing.JComboBox<String> CmbEspecialidad;
    private javax.swing.JLabel LbCedula1;
    private javax.swing.JLabel LbContraseña;
    private javax.swing.JLabel LbContraseña1;
    private javax.swing.JLabel LbNick;
    private javax.swing.JLabel LbNick1;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JTextField TFApellido;
    private javax.swing.JTextField TfCedula1;
    private javax.swing.JTextField TxtAños;
    private javax.swing.JTextField TxtEdad1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
