/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo2;

import Clases.*;
import Logica.ServicioProyecto;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;

public class ConsultaProyectosPorIngeniero extends javax.swing.JInternalFrame {

    private JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
    private Dimension dimBarra = null;
    ServicioProyecto sProyecto = new ServicioProyecto();
    Respuesta<ListaProyecto> respuesta;
    DefaultTableModel modeloTabla;

    public void ocultarBarraTitulo() {
        Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();

    }

    public ConsultaProyectosPorIngeniero() {
        initComponents();
        this.ocultarBarraTitulo();
        respuesta = new Respuesta(new ListaProyecto());
        this.ConsultarProyectos();
        this.CrearModeloDeTabla();
        this.Insertar();
    }

    private void ConsultarProyectos() {
        respuesta = sProyecto.ConsultarProyectosEnDesarrollo();
        if (!respuesta.isError()) {

        } else {
            Mensaje.MostrarNotificacion(respuesta.getMensaje());
        }
    }

    public void CrearModeloDeTabla() {
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Fecha de Inicio");
        modeloTabla.addColumn("Fecha Final");
        modeloTabla.addColumn("Cantidad Completado");
        modeloTabla.addColumn("Estado");
        this.TbProyectos.setModel(modeloTabla);
    }

    public void Insertar() {
        if (TbProyectos != null) {
            this.respuesta.getObjeto().getproyectos().forEach(proyecto -> {
                InsertarFila(proyecto);
            });
        }
    }

    public void InsertarFila(Proyecto proyecto) {
        String[] datos = new String[5];
        datos[0] = proyecto.getNombre();
        datos[1] = proyecto.ObtenerFecharCorta(proyecto.getFechaInicio());
        datos[2] = proyecto.ObtenerFecharCorta(proyecto.getFechaLimite());
        datos[3] = String.valueOf(proyecto.ObtenerPorcentajeTareaRealizadas()*100 + "%");
        datos[4] = String.valueOf(proyecto.getEstado());
        modeloTabla.addRow(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProyectos = new javax.swing.JTable();
        BtnVisualizarProyecto = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        TxtCedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabelTitulo.setText("Consutla de Proyectos en Desarrollo");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1010, 10));

        TbProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbProyectos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 690, 330));

        BtnVisualizarProyecto.setText("Visualizar Proyecto Seleccionado");
        BtnVisualizarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVisualizarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVisualizarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 230, 40));

        BtnBuscar.setText("Buscar Proyectos");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 230, 40));
        getContentPane().add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, 20));

        jLabel1.setText("Cédula del ingeniero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVisualizarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVisualizarProyectoActionPerformed
        if (TbProyectos.getSelectedRows().length == 1) {
            int indice = TbProyectos.getSelectedRow();
            Proyecto proyecto = this.respuesta.getObjeto().getproyectos().get(indice);
            Mensaje.MostrarNotificacion(proyecto.getNombre());
        }
        else if (TbProyectos.getSelectedRows().length == 0) 
            Mensaje.MostrarNotificacion("Advertencia: seleccione por lo menos un proyecto");
        else Mensaje.MostrarNotificacion("Advertencia: debe seleccionar solo un proyecto");
    }//GEN-LAST:event_BtnVisualizarProyectoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        if (TxtCedula.getText() != "") {
            
        }
        else Mensaje.MostrarNotificacion("Advertencia: Debe digitar la cedula del ingeniero a consultar");
    }//GEN-LAST:event_BtnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnVisualizarProyecto;
    private javax.swing.JTable TbProyectos;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
