/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo2;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
    

public class PrincipalAdmistrador extends javax.swing.JFrame {
    
    public PrincipalAdmistrador() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnRegistrarProyecto = new javax.swing.JButton();
        btonRegistrarUser = new javax.swing.JButton();
        BtonRegistrarIngeniero = new javax.swing.JButton();
        BtonRegistrarAdministrador = new javax.swing.JButton();
        BtnGestionarIngeniero = new javax.swing.JButton();
        BtnConsultarProyectos = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnConsultarProyectosPorIngeniero = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 64, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegistrarProyecto.setBackground(new java.awt.Color(45, 64, 89));
        BtnRegistrarProyecto.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtnRegistrarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrarProyecto.setText("Registrar Proyecto");
        BtnRegistrarProyecto.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtnRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarProyectoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 30));

        btonRegistrarUser.setBackground(new java.awt.Color(45, 64, 89));
        btonRegistrarUser.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        btonRegistrarUser.setForeground(new java.awt.Color(255, 255, 255));
        btonRegistrarUser.setText("Usuario Ingeniero");
        btonRegistrarUser.setMargin(new java.awt.Insets(0, 14, 0, 14));
        btonRegistrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonRegistrarUserActionPerformed(evt);
            }
        });
        jPanel1.add(btonRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 30));

        BtonRegistrarIngeniero.setBackground(new java.awt.Color(45, 64, 89));
        BtonRegistrarIngeniero.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtonRegistrarIngeniero.setForeground(new java.awt.Color(255, 255, 255));
        BtonRegistrarIngeniero.setText("Registrar Ingeniero");
        BtonRegistrarIngeniero.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtonRegistrarIngeniero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonRegistrarIngenieroActionPerformed(evt);
            }
        });
        jPanel1.add(BtonRegistrarIngeniero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 30));

        BtonRegistrarAdministrador.setBackground(new java.awt.Color(45, 64, 89));
        BtonRegistrarAdministrador.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtonRegistrarAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        BtonRegistrarAdministrador.setText("Usuario Administrador");
        BtonRegistrarAdministrador.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtonRegistrarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonRegistrarAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(BtonRegistrarAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 30));

        BtnGestionarIngeniero.setBackground(new java.awt.Color(45, 64, 89));
        BtnGestionarIngeniero.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtnGestionarIngeniero.setForeground(new java.awt.Color(255, 255, 255));
        BtnGestionarIngeniero.setText("Gestionar Ingeniero");
        BtnGestionarIngeniero.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtnGestionarIngeniero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionarIngenieroActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGestionarIngeniero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 30));

        BtnConsultarProyectos.setBackground(new java.awt.Color(45, 64, 89));
        BtnConsultarProyectos.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtnConsultarProyectos.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultarProyectos.setText("Consultar Proyectos");
        BtnConsultarProyectos.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtnConsultarProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarProyectosActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConsultarProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 220, 30));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 60, -1));

        BtnConsultarProyectosPorIngeniero.setBackground(new java.awt.Color(45, 64, 89));
        BtnConsultarProyectosPorIngeniero.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        BtnConsultarProyectosPorIngeniero.setForeground(new java.awt.Color(255, 255, 255));
        BtnConsultarProyectosPorIngeniero.setText("Proyectos Por Ingeniero");
        BtnConsultarProyectosPorIngeniero.setMargin(new java.awt.Insets(0, 14, 0, 14));
        BtnConsultarProyectosPorIngeniero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarProyectosPorIngenieroActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConsultarProyectosPorIngeniero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 710));

        escritorio.setPreferredSize(new java.awt.Dimension(1000, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 990, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtonRegistrarIngenieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonRegistrarIngenieroActionPerformed
        AbrirPanel(new RegistrarIngeniero());   
    }//GEN-LAST:event_BtonRegistrarIngenieroActionPerformed

    private void BtnRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarProyectoActionPerformed
        AbrirPanel(new RegistroProyecto());
    }//GEN-LAST:event_BtnRegistrarProyectoActionPerformed

    private void btonRegistrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonRegistrarUserActionPerformed
        AbrirPanel(new RegistroUsuarioIngenieroForm());
    }//GEN-LAST:event_btonRegistrarUserActionPerformed

    private void BtonRegistrarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonRegistrarAdministradorActionPerformed
        AbrirPanel(new RegistroUsuarioAdministradorForm());
    }//GEN-LAST:event_BtonRegistrarAdministradorActionPerformed

    private void BtnGestionarIngenieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionarIngenieroActionPerformed
        AbrirPanel(new GestionarIngeniero());
    }//GEN-LAST:event_BtnGestionarIngenieroActionPerformed

    private void BtnConsultarProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarProyectosActionPerformed
        AbrirPanel(new ConsultaProyectos());
    }//GEN-LAST:event_BtnConsultarProyectosActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        AbrirFormulario(new LoginForm());
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnConsultarProyectosPorIngenieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarProyectosPorIngenieroActionPerformed
        AbrirPanel(new ConsultaProyectosPorIngeniero());
    }//GEN-LAST:event_BtnConsultarProyectosPorIngenieroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultarProyectos;
    private javax.swing.JButton BtnConsultarProyectosPorIngeniero;
    private javax.swing.JButton BtnGestionarIngeniero;
    private javax.swing.JButton BtnRegistrarProyecto;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtonRegistrarAdministrador;
    private javax.swing.JButton BtonRegistrarIngeniero;
    private javax.swing.JButton btonRegistrarUser;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void AbrirPanel(JInternalFrame formularioInterno)
    {
        PrincipalAdmistrador.escritorio.add(formularioInterno);
        formularioInterno.setVisible(true);
    }
    public void AbrirFormulario(Frame formulario)
    {
        formulario.setVisible(true);
        this.dispose();
    }
}
